name: Advent Challenge

on:
  workflow_dispatch:

jobs:
  run-vxf-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check vxf
        uses: actions/checkout@master
        with:
          repository: vxf/AdventOfCode
          path: vxf

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run vxf python
        run: find ./2021 -name 'solve.py' -exec time python {} \;
        working-directory: vxf

  run-falso-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Check falsovsky
        uses: actions/checkout@master
        with:
          repository: falsovsky/advent2021
          path: falso

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
  
      - name: Run falso rust
        run: >-
          for file in ./src/*.rs;
          do
            echo "$file";
            file=$(basename -- "$file");
            echo "$file";
            file="${file%.*}";
            echo "$file";
            cargo build --bin "$file";
            time cargo run --bin "$file";
          done
        working-directory: falso

  run-trex:
    runs-on: ubuntu-latest
    steps:
      - name: Check trex
        uses: actions/checkout@master
        with:
          repository: t-recx/aoc2021
          path: trex

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
